### ISSUE TITLE
Monitoring multiple hosts

### ISSUE THREAD

**Issue by gansbrest** [RuntimeTools/appmetrics-statsd#3]
Hi,

It seems like if we need to monitor multiple servers, all metrics will be jumbled together, because there is no separtation key ( hostname? ). There will be no way to drill down into individual servers in graphite with the way mertics are named.

Also question about cluster mode, if we are running with pm2 in cluster mode with let say 8 node instances, will it send metrics for each node process, or only from master process?

**Comment by cidrblock** [comment]
try this, it will add a prefix to the metrics.

```
var statsd = require('appmetrics-statsd').StatsD('', 'localhost', 8125, 'node1\.');
```

**Comment by sjanuary** [comment]
Closing as a solution was found
