### ISSUE TITLE
Cannot configure appmetrics

### ISSUE THREAD

**Issue by imranbohoran** [RuntimeTools/appmetrics-statsd#5]
We want to use appmetrics-statsd and want to configure appmetrics to disable mqtt. I can't seem to do this currently when initialising the appmetrics-statsd library.

Ideally it would be nice to have two types of config objects passed into the appmetrics-statsd library so that both appmetrics and statsd can be configured. We are happy to raise a PR for this, but want to find out if this project is still maintained as there seem to be a PR that has been opened since early May.

**Comment by tobespc** [comment]
Hi, we are just putting a change in at the moment to appmetrics that will allow you to disable mqtt

**Comment by imranbohoran** [comment]
Thanks. Much appreciated.

**Comment by sjanuary** [comment]
Appmetrics can now disable mqtt via editing `appmetrics.properties` since version 1.1.1
