### ISSUE TITLE
How to use this with grafana?

### ISSUE THREAD

**Issue by Cidaas** [RuntimeTools/appmetrics-statsd#6]
Hi all, 

How to use this with grafana? I am not able to configure with grafana. please point me some tutorial.

**Comment by mattcolegate** [comment]
https://developer.ibm.com/open/2015/07/20/using-statsd-with-node-application-metrics/ has some links to help you get StatsD information into Graphite.

http://docs.grafana.org/features/datasources/graphite/ tells you how to get the information from Graphite into Grafana.

Hope that helps!
