### ISSUE TITLE
Is this repo still maintained?

### ISSUE THREAD

**Issue by maxcbc** [RuntimeTools/appmetrics-statsd#7]
Hi,

I was wondering whether this project is still maintained, as it is now 2 major versions behind `appmetrics`?

Is there any plan to update it or is it a case of raising a PR?

**Comment by tobespc** [comment]
It is maintained but on an ad-hoc basis right now.  It will automatically get the latest appmetrics when you install it though

**Comment by tobespc** [comment]
however, it is behind in some of the data that we can now collect.  Is there anything in particular you wanted added ?

**Comment by tobespc** [comment]
ok, I see its failing to pull in latest appmetrics, fixing now....

**Comment by maxcbc** [comment]
Not specifically. I was just thrown by the `"appmetrics": "^1.0.4"` in package.json. I got the impression that It wouldn't support any semver major versions above 1.x. Though that's clearly my misunderstanding

**Comment by maxcbc** [comment]
Ahh I see, awesome thanks @tobespc

**Comment by tobespc** [comment]
@maxcbc All done, I will update to npmjs later but you can install from git for now
